server.port=8090
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

bank.simulator.base-url=http://localhost:8080
bank.simulator.payments-path=/payments
bank.simulator.connect-timeout-ms=2000
bank.simulator.read-timeout-ms=2000

logging.pattern.level=%5p [requestId=%X{requestId}]
management.endpoints.web.exposure.include=health,info,metrics
